routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/', "PageController@home")->name("index");


Route::get('{id}-{name}.html',"PageController@page")->name('a.page');
Route::get('{id}-{name}/{id2}-{name2}.html',"PageController@pagedetail")->name('a.pagedetail');
Route::post('{id}-{name}.html',"PageController@pagepost");

Route::resource('appointment','AppointmentController');
Route::resource('payment','PaymentController');

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('ajax/hour', 'AjaxController@hour')->name('hour');


Route::group(["middleware" => ["rolecheck:admin","auth"]], function () {
    
    Route::group(['namespace' => 'Admin'], function () {
        Route::resource('admin/page', 'PageController');
        Route::post('admin/page/order', 'PageController@order')->name('page.order');
        Route::get('admin/page/status/{page}', 'PageController@status')->name('page.status');

        Route::get('admin/page/{page}/home', 'PageController@home')->name('page.home');

        Route::get('admin/lang/{id}', 'Lang@index')->name('admin.lang');
        Route::resource('admin/pagecontent', 'PageContentController');
        Route::post('admin/pagecontent/order', 'PageContentController@order')->name('pagecontent.order');
        Route::get('admin/pagecontent/status/{pagecontent}', 'PageContentController@status')->name('pagecontent.status');
        Route::post('admin/pagecontetupload', 'PageContentController@contetupload')->name('contetupload.image');

        Route::resource('admin/team', 'TeamController');
        Route::post('image/team', 'TeamController@image_upload')->name('team.image');
        Route::put('image/team', 'TeamController@image_upload')->name('team.image');
        Route::post('imageremove/team', 'TeamController@image_remove')->name('team.imageremove');
        Route::post('admin/team/order', 'TeamController@order')->name('team.order');
        Route::get('admin/team/status/{team}', 'TeamController@status')->name('team.status');


        Route::resource('admin/sponsor', 'sponsorController');
        Route::post('image/sponsor', 'sponsorController@image_upload')->name('sponsor.image');
        Route::put('image/sponsor', 'sponsorController@image_upload')->name('sponsor.image');
        Route::post('imageremove/sponsor', 'sponsorController@image_remove')->name('sponsor.imageremove');
        Route::post('admin/sponsor/order', 'sponsorController@order')->name('sponsor.order');
        Route::get('admin/sponsor/status/{sponsor}', 'sponsorController@status')->name('sponsor.status');

        Route::resource('admin/setting', 'SettingController');
        Route::resource('admin/slider', 'SliderController');
        Route::post('admin/slider/order', 'SliderController@order')->name('slider.order');
        Route::get('admin/slider/status/{slider}', 'SliderController@status')->name('slider.status');

        Route::post('image/slider', 'SliderController@image_upload')->name('slider.image');

        Route::resource('admin/contentfile', 'ContentFileController');

        Route::post('image/contentfile', 'ContentFileController@image_upload')->name('contentfile.image');
        Route::put('image/contentfile', 'ContentFileController@image_upload')->name('contentfile.image');
        Route::post('imageremove/contentfile', 'ContentFileController@image_remove')->name('contentfile.imageremove');     

        Route::resource('admin/package', 'packageController');
        Route::post('admin/package/order', 'packageController@order')->name('package.order');
        Route::get('admin/package/status/{package}', 'packageController@status')->name('package.status');

        Route::resource('admin/time', 'TimeController');

    });
});

Route::get('lang/{id}', 'Lang@index')->name('lang');

resources/views/admin/page/create.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="box box-primary">
	<div class="box-header with-border">
	  <h3 class="box-title">Page Add</h3>
	</div>
	
	{!! Form::open(['url' => 'admin/page', 'method' => "POST", "class" =>"smart-form", 'files' => true,'role'=>'form']) !!}

		<div class="box-body">
			{{ Form::dText('title','Title') }}
			{{ Form::dText('meta_desc','Meta Des.') }}
			{{ Form::dText('meta_keyword','Meta Keyword') }}
			{{ Form::dText('redirect_url','Redirect URL') }}
			{{ Form::dSelect('page_type_id','Page Type',$pagetypes) }}
			{{ Form::dCheckboxone('topmenu','Top Menu',1,null) }}
			{{ Form::dCheckboxone('submenu','Bottom Menu',1,null) }}
			{{ Form::hidden('page_id', $page_id) }}
			{{ Form::dFile('page_img','Image') }}
		</div>
		<div class="box-footer">
			{{ Form::dSubmit('save','Insert') }}
		</div>
	{!! Form::close() !!}
</div>

@endsection

resources/views/admin/page/edit.blade.php
@extends('admin.layouts.app')

@section('content')
{!! Form::model($page, ['route' => ['page.update' ,$page->id,  'page_id' => $page->page_id ], 'method' => "put", "class" =>"smart-form", 'files' => true,'role'=>'form']) !!}
		<div class="box-body">
<div class="box box-primary">
	<div class="box-header with-border">
		<h3 class="box-title">Page Edit</h3>
	</div>
	
			{{ Form::dText('title','Title') }}
			{{ Form::dText('meta_desc','Meta Des.') }}
			{{ Form::dText('meta_keyword','Meta Keyword') }}
			{{ Form::dText('redirect_url','Redirect URL') }}
			{{ Form::dSelect('page_type_id','Page Type',$pagetypes) }}
			{{ Form::dCheckboxone('topmenu','Top Menu',1,null) }}
			{{ Form::dCheckboxone('submenu','Bottom Menu',1,null) }}
			{{ Form::hidden('page_id') }}
			{{ Form::dFile('page_img','Image') }}
		</div>
		<div class="box-footer">
			{{ Form::dSubmit('save','Update') }}
		</div>
	
</div>
{!! Form::close() !!}
@endsection

resources/views/admin/page/index.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="row">
				<div class="col-md-12">
					<a class="btn btn-primary" href="{{ route('page.create',[Null,'page_id'=>$page_id]) }}" style="float: right;margin: 10px 0px;">Add</a>
				</div>
			</div>
			<div class="box">
				<div class="box-header with-border">
				<h3 class="box-title">Pages</h3>
				</div>
				<div class="box-body">
					{!! Form::open(['route' => ['page.order', Null,  'page_id' => $page_id], 'method' => "POST",]) !!}
							
						<table class="table table-bordered">
							<thead>
								<tr>
									<th style="width: 50px;">Short NO</th>
									@if ($page_id==0)
									<th>Home Page</th>									
									@endif
									<th>Page Name</th>
									<th style="width: 10px;">Status</th>
									<th>Action</th>
								</tr>
							</thead>

							@if ($pages)
								<tbody>
									@foreach ($pages as $page)
										<tr>
											<td >{{ Form::dText2('order['.$page->id.']','',null,$page->order,['style'=> 'width: 50px;text-align: center;']) }}</td>
											@if ($page_id==0)
										<td style="width: 100px; text-align:center;"><a href="{{ route('page.home', ['id'=>$page->id]) }}">@php
											if($page->homepage==1){ $color="yellow"; }else{ $color="#c5c5c5"; }
										@endphp<i class="fa fa-star" style="color:{{ $color }};font-size: 22px;"></i></a></td>
											@endif
										
											<td><a href="{{ route('page.index', [null,'page_id'=>$page->id]) }}">{{$page->title}}</a></td>
											<td style="text-align: center;">
												<a href="{{ route('page.status', ['page_id'=>$page->id] ) }}">@if ($page->status==1) <i class="fa fa-eye" style="color:#356635;    font-size: 19px;"></i> @else <i class="fa fa-eye-slash" style="color:red;font-size: 19px;"></i> @endif</a>
											</td>
											<td>
												@if ($page->page_type->path=='team')
													<a href="{{ route('team.index', ['page_id'=>$page->id] ) }}" class="btn btn-primary action"><i class="fa fa-list"></i></a>
												@endif
												@if ($page->page_type->path == "sponsor")
													<a href="{{ route('sponsor.index', ['page_id'=>$page->id] ) }}" class="btn btn-primary action"><i class="fa fa-list"></i></a>
												@endif
												@if ($page->page_type->path == "tourgroup")
													<a href="{{ route('tourgroup.index', ['page_id'=>$page->id] ) }}" class="btn btn-primary action"><i class="fa fa-list"></i></a>
												@endif
												@if ($page->page_type->path == "pagecategory")
													<a href="{{ route('pagecategory.index', ['page_id'=>$page->id] ) }}" class="btn btn-primary action"><i class="fa fa-list"></i></a>
												@endif
												@if ($page->page_type->path == "pagecategorydetail")
													<a href="{{ route('pagecategorydetail.index', ['page_id'=>$page->id] ) }}" class="btn btn-primary action"><i class="fa fa-list"></i></a>
												@endif
												<a href="{{ route('pagecontent.index', [null,'type' => $page->page_type_id,'oid'=>$page->id]) }}" class="btn btn-primary action"><i class="fa fa-file"></i></a>
												<a href="{{ route('page.edit', ['id'=>$page->id]) }}" class="btn btn-primary action">Edit</a>
												<a href="{{ route('page.destroy', ['id'=>$page->id]) }}" data-method="delete" data-token="{{csrf_token()}}" data-confirm="Are you sure it will be deleted?" class="btn btn-danger action">Delete</a>
											</td>
										</tr>
									@endforeach
									<tr>
										<td>{{ Form::dSubmit('save','Short Save') }}</td>
										@if ($page_id==0)
										<td colspan="4"></td>
										@else
										<td colspan="3"></td>
										@endif
									</tr>
								</tbody>
							@endif
						</table>
						{!! Form::close() !!}

					</div>
			</div>
		</div>
	</div>	
</div>
@endsection

resources/views/admin/page/report.blade.php
@extends('layouts.master')

@section('content')
<div class="right_col" role="main">
<div class="container">
    <div class="row">
    	<div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
            	<div class="x_title">
            		 <h2>Siteler</h2>
            		 <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>

            	</div>
      {!! Form::open(['route' => ['site.report'], 'method' => "get",]) !!}
            <?php 
            $totaltraffic =0;
            $totalunique_traffic =0;
            
             ?> 
              <div class="col-sm-12">
                <div class="row">
                      <?php $tlist = array();
                      $tp=array();
                      $tpu=array();
          foreach ($devices as $key => $element){

            $tlist[] = array('value' => $key,'text' => $element,'is_checked' =>false);
          } ?>
                      <div class="col-sm-3">{{ Form::dCheckbox2('device','Cihaz',$tlist) }}</div>
                      <div class="col-sm-3">{{ Form::dSelectm2('tags[]','Etiket',$tags) }}</div>
                      <div class="col-sm-3">  {{ Form::dSubmit('save','Ara') }}</div>
                  </div>
              </div>
            	<div class="x_content">
            		<table id="datatable-buttons" class="table table-striped table-bordered">
            			<thead>
                        <tr>
                          <th rowspan="2">Site Adı</th>
                          <th rowspan="2">Trafik</th>
                          @if ($codes)
                            @foreach ($codes as $item)
                                <?php 
                                $tp[format_slug($item->name)] =0; 
                                $tpu[format_slug($item->name)] =0; 
                                ?>
                              <th colspan="2" style="text-align: center;">{{ $item->name }}</th>
                            @endforeach
                          @endif
                        </tr>
                        <tr>
                           @if ($codes)
                            @foreach ($codes as $item)
                            <th>CPM</th>
                            <th>CPC</th>
                            @endforeach
                          @endif
                        </tr>
                      </thead>

					@if ($sites)
					<tbody>
						@foreach ($sites as $site)
						<tr>
                        <td>{{$site->site_name}}</td>
						<td>{{$site->traffic.' / '. $site->unique_traffic}}</td>
                        <?php 
                        $totaltraffic+=$site->traffic;
                        $totalunique_traffic+=$site->unique_traffic;
                        
                         ?>
              @if ($codes)
                @foreach ($codes as $item)
                
                    <?php 
                    $cpm = $site->site_prices->where('code_id',$item->id)->first()['cpm_price'];
                    $cpc = $site->site_prices->where('code_id',$item->id)->first()['cpc_price'];
                    if ($site->traffic>0 && $cpm>0) {
                        $tp[format_slug($item->name)] +=( ($site->traffic/1000)*$cpm ); 
                        $tpu[format_slug($item->name)] =( ($site->unique_traffic/1000)*$cpm ); 
                    }
                    ?>
                   
                  <td>{{ number_format($cpm,2) }}</td>
                  <td>{{ number_format($cpc,2) }}</td>
                  
                @endforeach
              @endif
							
						</tr>
						@endforeach
                        <tr>
                            <td colspan="2" style="text-align: right;">Trafik ortalam / Unique ortalama: {{$totaltraffic.' / '.$totalunique_traffic}} </td>
                            @if ($codes)
                            @foreach ($codes as $item)
                                @if ($totaltraffic>0)
                                <td>{{ number_format(($tp[format_slug($item->name)]/($totaltraffic/1000)),2) }}</td>
                                <td>{{ number_format(($tpu[format_slug($item->name)]/($totalunique_traffic/1000)),2) }}</td>
                                @else
                                <td>{{ number_format(0,2) }}</td>
                                <td>{{ number_format(0,2) }}</td>
                                @endif
                                
                            @endforeach
                            @endif
                        </tr>
					</tbody>
                	@endif
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
@endsection
@section('js')
  <script type="text/javascript">
    $('.selectize').selectize({
      //createOnBlur: true,
        create: true,
        delimiter: ',',
        persist: false,
        plugins: ['remove_button'],

        });
  </script>
@endsection
<?php function remove_accents($string)
{
    $a = 'ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûýýþÿŔŕ';
    $b = 'aaaaaaaceeeeiiiidnoooooouuuuybsaaaaaaaceeeeiiiidnoooooouuuyybyRr';
    $string = strtr(utf8_decode($string), utf8_decode($a), $b);
    return utf8_encode($string);
}

function format_slug($title)
{
    $title = remove_accents($title);
    $title = trim(strtolower($title));
    $title = preg_replace('#[^a-z0-9\\-/]#i', '_', $title);
    return trim(preg_replace('/-+/', '-', $title), '-/');
} ?>